#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

# Configure which branches trigger builds
trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - internal/release/*

# Run PR validation on all branches
pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _TeamName
  value:  AspNetCore

jobs:
- template: jobs/default-build.yml
  parameters:
    condition: ne(variables['SkipTests'], 'true')
    jobName: Components_E2E_Test
    jobDisplayName: "Test: Blazor E2E tests on Linux"
    agentOs: Linux
    installNodeJs: true
    installJdk: true
    isTestingJob: true
    steps:
    - script: git submodule update --init
      displayName: Update submodules
    - script: ./restore.sh
      displayName: Run restore.sh
    - script: npm install --prefix ./src/Components/test/E2ETest
      displayName: NPM install
    - script: .dotnet/dotnet build ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-restore
      displayName: Build
    - script: .dotnet/dotnet test ./src/Components/test/E2ETest -c $(BuildConfiguration) --no-build --logger trx
      displayName: Run E2E tests
    - task: PublishTestResults@2
      displayName: Publish E2E Test Results
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/src/Components/test/E2ETest/TestResults'
        testRunTitle: ComponentsE2E-$(AgentOsName)-$(BuildConfiguration)-xunit
      condition: always()
    artifacts:
    - name: Components_E2E_Test_Logs
      path: ./src/Components/test/E2ETest/TestResults
      publishOnError: true
